### ISSUE TITLE
Context usage

### ISSUE THREAD

**Issue by KenxinKun** [cassiuspaim/portimporter#1]
Hi Cassius, I'm Borja I've been asked to review this submission. I'll create some issues with questions as I go, here's the first one:

I can see that in the mongo repository, when implementing `GetByID` and using the mongo client `FindOne`, you're using a new `context.TODO()` (which I get, is unfinished). Link below for the line in question. The same pattern appears in the other repository implemented methods.

https://github.com/cassiuspaim/portimporter/blob/74028c55d4c641739f6de109c7fe6a848745cc36/infrastructure/repositories/mongodb/mongorepository.go#L82

Can you comment on how would you cancel this context from the core service layer that is using the repository? Would you do anything differently to be able to do so?

**Comment by cassiuspaim** [comment]
Hey @KenxinKun,

Nice to meet you Borja!
I will probably reply back the issues tonight(at Brasil), right now I am working. Please send all the issues and I will address as soon as I can.

**Comment by cassiuspaim** [comment]
I should have passed the context from the main and pass it to the downstream components, including the Port repository. With this change once the context is cancelled the mongo driver would close the connection and the pending method retrieves an error. 

Did I answer your question?

**Comment by KenxinKun** [comment]
Sounds good!
