### ISSUE TITLE
Dockerfile questions

### ISSUE THREAD

**Issue by KenxinKun** [cassiuspaim/portimporter#2]
Firstly, thanks for bundling up your proposed solution in a Dockerfile + compose file, it's very handy and has let me test everything much quicker :)

https://github.com/cassiuspaim/portimporter/blob/74028c55d4c641739f6de109c7fe6a848745cc36/Dockerfile#L22

I can see that you're using the Docker context itself from a base golang image to build the binaries (great!) and then run the resulting binary from the same image:

- What security concerns would still need addressing if you were to further work on this Dockerfile?
- How would you reduce the final image size, once you've already build the binary?

**Comment by cassiuspaim** [comment]
To decrease the image size and improve the security somethings could be done like:
- Choose a lightweight linux distribution as Alpine, this would reduce the image size and improve the security considering the Alpine image has less utilities;
- Be more specific about which version of Alpine to improve reliability and avoid unexpected behaviour.
- Use a multi-stage build, splitting the building process and the execution image, copying only what is needed from one image to a lighter one as scratch.
- Remove the DWARF tables and annotations adding the flags `-ldflags="-s -w"`

I believe this version would be something like this:

```
# syntax=docker/dockerfile:1

FROM golang:1.20-alpine3.17 as builder

WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /portimporter

FROM scratch
COPY --from=builder /app /app

CMD [ "/portimporter" ]
```

**Comment by KenxinKun** [comment]
Sounds great :) Just a final follow-up question on this: what permissions is the user in the Dockerfile running with?

**Comment by cassiuspaim** [comment]
The user that runs the dockerfile is root, so one thing to mitigate this would be create a less-privileged user with only the minimum privileges to follow the least privilege principle.

**Comment by KenxinKun** [comment]
Awesome, that fully answers this question :)
